---
- name: Ensure Python3 is installed
  hosts: all
  become: true
  tasks:
    - name: Install Python3 on Debian/Ubuntu
      apt:
        name: python3
        state: present
        update_cache: yes
      when: ansible_facts['os_family'] == "Debian"

    - name: Install Python3 on RedHat/CentOS/Fedora
      yum:
        name: python3
        state: present
      when: ansible_facts['os_family'] == "RedHat"

    - name: Install Python3 on SUSE
      zypper:
        name: python3
        state: present
      when: ansible_facts['os_family'] == "Suse"
